name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Compile
      run: make all

    - name: Generate patch
      run: git diff unpatched > "dwm-ipc-$(datetime +%Y%m%d)-$(git diff -s --format=%h).diff"

    - uses: actions/upload-artifact@v2
      with:
        name: patch
        path: ${{ github.workspace }}/*.diff

